import pandas as pd
import numpy as np

from datetime import timedelta, date

from typing import Optional, List

from data_warehouse_utils.dataloader import DataLoader


def get_medications(dl: DataLoader, df):

    df_medications = dl.get_medications(columns=['hash_patient_id',
                                                 'pacmed_name',
                                                 'pacmed_subname',
                                                 'start_timestamp',
                                                 'end_timestamp',
                                                 'total_dose',
                                                 'dose_unit_name'])

    medications = (df_medications['pacmed_name'].isin(MEDICATIONS)) | \
                  (df_medications['pacmed_subname'].isin(MEDICATIONS))

    df_medications = df_medications.loc[medications]

    interval_start = 4 # hours before proning starts to look for medications
    interval_end = 2 # hours after proning started to look for medication

    df_measurements = [get_medication_per_session(df_medications=df_medications,
                                                  hash_session_id=row.hash_session_id,
                                                  hash_patient_id=row.hash_patient_id,
                                                  start_timestamp=row.start_timestamp,
                                                  interval_start=interval_start,
                                                  interval_end=interval_end) for idx, row in df.iterrows()]

    if df_measurements:
        df_measurements = pd.concat(df_measurements)
        df_measurements.reset_index(inplace=True)
        if 'index' in df_measurements.columns:
            df_measurements.rename(columns={"index": "hash_session_id"}, inplace=True)
        df = pd.merge(df, df_measurements, how='left', on='hash_session_id')

    return df


def get_medication_per_session(df_medications,
                               hash_session_id,
                               hash_patient_id,
                               start_timestamp,
                               interval_start,
                               interval_end):

    start = start_timestamp - timedelta(hours=4)
    end = start_timestamp + timedelta(hours=2)

    timestamp_matches = (start <= df_medications['start_timestamp']) & (df_medications['start_timestamp'] <= end)
    id_matches = df_medications['hash_patient_id'] == hash_patient_id
    mask = timestamp_matches & id_matches

    df_medications = df_medications[mask]

    atc_all = [N01, N05, M03, C01C, N02A, B01AA, B01AB, B01AE, B01AF, B01AX, C03C, R05C, R03A,
               R03B, C01CA03, C01CA04, C01CA24, H01BA01, H01BA04, H02A]

    atc_all_names = ['N01', 'N05', 'M03', 'C01C', 'N02A', 'B01AA', 'B01AB', 'B01AE', 'B01AF', 'B01AX', 'C03C', 'R05C',
                     'R03A', 'R03B', 'C01CA03', 'C01CA04', 'C01CA24', 'H01BA01', 'H01BA04', 'H02A']

    df_measurements = pd.DataFrame([],columns=list(map('atc_'.__add__, atc_all_names)))

    for idx, atc in enumerate(atc_all):
        column_name = 'atc_{}'.format(atc_all_names[idx])
        if set(df_medications.pacmed_name.unique()) & (set(atc)):
            df_measurements.loc[hash_session_id, column_name] = True
        else:
            if set(df_medications.pacmed_subname.unique()) & (set(atc)):
                df_measurements.loc[hash_session_id, column_name] = True
            else:
                df_measurements.loc[hash_session_id, column_name] = False

    return df_measurements


N01 = ['med_anesthetics',
       'med_anesthetics_general',
       'med_ethers',
       'med_diethyl_ether',
       'med_vinyl_ether',
       'med_halogenated_hydrocarbons',
       'med_halothane',
       'med_chloroform',
       'med_enflurane',
       'med_trichloroethylene',
       'med_isoflurane',
       'med_desflurane',
       'med_sevoflurane',
       'med_barbiturates_plain',
       'med_methohexital',
       'med_hexobarbital',
       'med_thiopental',
       'med_barbiturates_in_combination_with_other_drugs',
       'med_narcobarbital',
       'med_opioid_anesthetics',
       'med_fentanyl',
       'med_alfentanil',
       'med_sufentanil',
       'med_phenoperidine',
       'med_anileridine',
       'med_remifentanil',
       'med_fentanyl_combinations',
       'med_other_general_anesthetics',
       'med_ketamine',
       'med_propanidid',
       'med_alfaxalone',
       'med_etomidate',
       'med_propofol',
       'med_sodium_oxybate',
       'med_nitrous_oxide',
       'med_esketamine',
       'med_xenon',
       'med_nitrous_oxide_combinations',
       'med_anesthetics_local',
       'med_esters_of_aminobenzoic_acid',
       'med_metabutethamine',
       'med_procaine',
       'med_tetracaine',
       'med_chloroprocaine',
       'med_benzocaine',
       'med_procaine_combinations',
       'med_tetracaine_combinations',
       'med_amides',
       'med_bupivacaine',
       'med_lidocaine',
       'med_mepivacaine',
       'med_prilocaine',
       'med_butanilicaine',
       'med_cinchocaine',
       'med_etidocaine',
       'med_articaine',
       'med_ropivacaine',
       'med_levobupivacaine',
       'med_combinations',
       'med_bupivacaine_combinations',
       'med_lidocaine_combinations',
       'med_mepivacaine_combinations',
       'med_prilocaine_combinations',
       'med_etidocaine_combinations',
       'med_articaine_combinations',
       'med_esters_of_benzoic_acid',
       'med_cocaine',
       'med_other_local_anesthetics',
       'med_ethyl_chloride',
       'med_dyclonine',
       'med_phenol',
       'med_capsaicin']

N05 = ['med_psycholeptics',
       'med_antipsychotics',
       'med_phenothiazines_with_aliphatic_side-chain',
       'med_chlorpromazine',
       'med_levomepromazine',
       'med_promazine',
       'med_acepromazine',
       'med_triflupromazine',
       'med_cyamemazine',
       'med_chlorproethazine',
       'med_phenothiazines_with_piperazine_structure',
       'med_dixyrazine',
       'med_fluphenazine',
       'med_perphenazine',
       'med_prochlorperazine',
       'med_thiopropazate',
       'med_trifluoperazine',
       'med_acetophenazine',
       'med_thioproperazine',
       'med_butaperazine',
       'med_perazine',
       'med_phenothiazines_with_piperidine_structure',
       'med_periciazine',
       'med_thioridazine',
       'med_mesoridazine',
       'med_pipotiazine',
       'med_butyrophenone_derivatives',
       'med_haloperidol',
       'med_trifluperidol',
       'med_melperone',
       'med_moperone',
       'med_pipamperone',
       'med_bromperidol',
       'med_benperidol',
       'med_droperidol',
       'med_fluanisone',
       'med_indole_derivatives',
       'med_oxypertine',
       'med_molindone',
       'med_sertindole',
       'med_ziprasidone',
       'med_lurasidone',
       'med_thioxanthene_derivatives',
       'med_flupentixol',
       'med_clopenthixol',
       'med_chlorprothixene',
       'med_tiotixene',
       'med_zuclopenthixol',
       'med_diphenylbutylpiperidine_derivatives',
       'med_fluspirilene',
       'med_pimozide',
       'med_penfluridol',
       'med_diazepines_oxazepines_thiazepines_and_oxepines',
       'med_loxapine',
       'med_clozapine',
       'med_olanzapine',
       'med_quetiapine',
       'med_asenapine',
       'med_clotiapine',
       'med_benzamides',
       'med_sulpiride',
       'med_sultopride',
       'med_tiapride',
       'med_remoxipride',
       'med_amisulpride',
       'med_veralipride',
       'med_levosulpiride',
       'med_lithium',
       'med_lithium',
       'med_other_antipsychotics',
       'med_prothipendyl',
       'med_risperidone',
       'med_mosapramine',
       'med_zotepine',
       'med_aripiprazole',
       'med_paliperidone',
       'med_iloperidone',
       'med_cariprazine',
       'med_brexpiprazole',
       'med_pimavanserin',
       'med_anxiolytics',
       'med_benzodiazepine_derivatives',
       'med_diazepam',
       'med_chlordiazepoxide',
       'med_medazepam',
       'med_oxazepam',
       'med_potassium_clorazepate',
       'med_lorazepam',
       'med_adinazolam',
       'med_bromazepam',
       'med_clobazam',
       'med_ketazolam',
       'med_prazepam',
       'med_alprazolam',
       'med_halazepam',
       'med_pinazepam',
       'med_camazepam',
       'med_nordazepam',
       'med_fludiazepam',
       'med_ethyl_loflazepate',
       'med_etizolam',
       'med_clotiazepam',
       'med_cloxazolam',
       'med_tofisopam',
       'med_bentazepam',
       'med_lorazepam_combinations',
       'med_diphenylmethane_derivatives',
       'med_hydroxyzine',
       'med_captodiame',
       'med_hydroxyzine_combinations',
       'med_carbamates',
       'med_meprobamate',
       'med_emylcamate',
       'med_mebutamate',
       'med_meprobamate_combinations',
       'med_dibenzo-bicyclo-octadiene_derivatives',
       'med_benzoctamine',
       'med_azaspirodecanedione_derivatives',
       'med_buspirone',
       'med_other_anxiolytics',
       'med_mephenoxalone',
       'med_gedocarnil',
       'med_etifoxine',
       'med_fabomotizole',
       'med_lavandulae_aetheroleum',
       'med_hypnotics_and_sedatives',
       'med_barbiturates_plain',
       'med_pentobarbital',
       'med_amobarbital',
       'med_butobarbital',
       'med_barbital',
       'med_aprobarbital',
       'med_secobarbital',
       'med_talbutal',
       'med_vinylbital',
       'med_vinbarbital',
       'med_cyclobarbital',
       'med_heptabarbital',
       'med_reposal',
       'med_methohexital',
       'med_hexobarbital',
       'med_thiopental',
       'med_etallobarbital',
       'med_allobarbital',
       'med_proxibarbal',
       'med_barbiturates_combinations',
       'med_combinations_of_barbiturates',
       'med_barbiturates_in_combination_with_other_drugs',
       'med_aldehydes_and_derivatives',
       'med_chloral_hydrate',
       'med_chloralodol',
       'med_acetylglycinamide_chloral_hydrate',
       'med_dichloralphenazone',
       'med_paraldehyde',
       'med_benzodiazepine_derivatives',
       'med_flurazepam',
       'med_nitrazepam',
       'med_flunitrazepam',
       'med_estazolam',
       'med_triazolam',
       'med_lormetazepam',
       'med_temazepam',
       'med_midazolam',
       'med_brotizolam',
       'med_quazepam',
       'med_loprazolam',
       'med_doxefazepam',
       'med_cinolazepam',
       'med_remimazolam',
       'med_piperidinedione_derivatives',
       'med_glutethimide',
       'med_methyprylon',
       'med_pyrithyldione',
       'med_benzodiazepine_related_drugs',
       'med_zopiclone',
       'med_zolpidem',
       'med_zaleplon',
       'med_eszopiclone',
       'med_melatonin_receptor_agonists',
       'med_melatonin',
       'med_ramelteon',
       'med_tasimelteon',
       'med_other_hypnotics_and_sedatives',
       'med_methaqualone',
       'med_clomethiazole',
       'med_bromisoval',
       'med_carbromal',
       'med_scopolamine',
       'med_propiomazine',
       'med_triclofos',
       'med_ethchlorvynol',
       'med_valerianae_radix',
       'med_hexapropymate',
       'med_bromides',
       'med_apronal',
       'med_valnoctamide',
       'med_methylpentynol',
       'med_niaprazine',
       'med_dexmedetomidine',
       'med_suvorexant',
       'med_hypnotics_and_sedatives_in_combination_excl_barbiturates',
       'med_meprobamate_combinations',
       'med_methaqualone_combinations',
       'med_methylpentynol_combinations',
       'med_clomethiazole_combinations',
       'med_emepronium_combinations',
       'med_dipiperonylaminoethanol_combinations']

M03 = ['med_muscle_relaxants',
       'med_muscle_relaxants_peripherally_acting_agents',
       'med_curare_alkaloids',
       'med_alcuronium',
       'med_tubocurarine',
       'med_dimethyltubocurarine',
       'med_choline_derivatives',
       'med_suxamethonium',
       'med_other_quaternary_ammonium_compounds',
       'med_pancuronium',
       'med_gallamine',
       'med_vecuronium',
       'med_atracurium',
       'med_hexafluronium',
       'med_pipecuronium_bromide',
       'med_doxacurium_chloride',
       'med_fazadinium_bromide',
       'med_rocuronium_bromide',
       'med_mivacurium_chloride',
       'med_cisatracurium',
       'med_other_muscle_relaxants_peripherally_acting_agents',
       'med_botulinum_toxin',
       'med_muscle_relaxants_centrally_acting_agents',
       'med_carbamic_acid_esters',
       'med_phenprobamate',
       'med_carisoprodol',
       'med_methocarbamol',
       'med_styramate',
       'med_febarbamate',
       'med_phenprobamate_combinations_excl_psycholeptics',
       'med_carisoprodol_combinations_excl_psycholeptics',
       'med_methocarbamol_combinations_excl_psycholeptics',
       'med_phenprobamate_combinations_with_psycholeptics',
       'med_carisoprodol_combinations_with_psycholeptics',
       'med_methocarbamol_combinations_with_psycholeptics',
       'med_oxazol_thiazine_and_triazine_derivatives',
       'med_chlormezanone',
       'med_chlorzoxazone',
       'med_chlormezanone_combinations_excl_psycholeptics',
       'med_chlorzoxazone_combinations_excl_psycholeptics',
       'med_chlormezanone_combinations_with_psycholeptics',
       'med_chlorzoxazone_combinations_with_psycholeptics',
       'med_ethers_chemically_close_to_antihistamines',
       'med_orphenadrine_(citrate)',
       'med_orphenadrine_combinations',
       'med_other_centrally_acting_agents',
       'med_baclofen',
       'med_tizanidine',
       'med_pridinol',
       'med_tolperisone',
       'med_thiocolchicoside',
       'med_mephenesin',
       'med_tetrazepam',
       'med_cyclobenzaprine',
       'med_eperisone',
       'med_fenyramidol',
       'med_thiocolchicoside_combinations',
       'med_muscle_relaxants_directly_acting_agents',
       'med_dantrolene_and_derivatives',
       'med_dantrolene']

C01C = ['med_cardiac_stimulants_excl_cardiac_glycosides',
        'med_adrenergic_and_dopaminergic_agents',
        'med_etilefrine',
        'med_isoprenaline',
        'med_norepinephrine',
        'med_dopamine',
        'med_norfenefrine',
        'med_phenylephrine',
        'med_dobutamine',
        'med_oxedrine',
        'med_metaraminol',
        'med_methoxamine',
        'med_mephentermine',
        'med_dimetofrine',
        'med_prenalterol',
        'med_dopexamine',
        'med_gepefrine',
        'med_ibopamine',
        'med_midodrine',
        'med_octopamine',
        'med_fenoldopam',
        'med_cafedrine',
        'med_arbutamine',
        'med_theodrenaline',
        'med_epinephrine',
        'med_amezinium_metilsulfate',
        'med_ephedrine',
        'med_droxidopa',
        'med_combinations',
        'med_etilefrine_combinations',
        'med_phosphodiesterase_inhibitors',
        'med_amrinone',
        'med_milrinone',
        'med_enoximone',
        'med_bucladesine',
        'med_other_cardiac_stimulants',
        'med_angiotensinamide',
        'med_xamoterol',
        'med_levosimendan',
        'med_angiotensin_ii']

N02A = ['med_opioids',
        'med_natural_opium_alkaloids',
        'med_morphine',
        'med_opium',
        'med_hydromorphone',
        'med_nicomorphine',
        'med_oxycodone',
        'med_dihydrocodeine',
        'med_papaveretum',
        'med_morphine_combinations',
        'med_hydromorphone_and_naloxone',
        'med_oxycodone_and_naloxone',
        'med_oxycodone_and_naltrexone',
        'med_dihydrocodeine_combinations',
        'med_codeine_combinations_excl_psycholeptics',
        'med_codeine_combinations_with_psycholeptics',
        'med_phenylpiperidine_derivatives',
        'med_ketobemidone',
        'med_pethidine',
        'med_fentanyl',
        'med_pethidine_combinations_excl_psycholeptics',
        'med_pethidine_combinations_with_psycholeptics',
        'med_diphenylpropylamine_derivatives',
        'med_dextromoramide',
        'med_piritramide',
        'med_dextropropoxyphene',
        'med_bezitramide',
        'med_methadone_combinations_excl_psycholeptics',
        'med_dextropropoxyphene_combinations_excl_psycholeptics',
        'med_dextropropoxyphene_combinations_with_psycholeptics',
        'med_benzomorphan_derivatives',
        'med_pentazocine',
        'med_phenazocine',
        'med_oripavine_derivatives',
        'med_buprenorphine',
        'med_morphinan_derivatives',
        'med_butorphanol',
        'med_nalbuphine',
        'med_opioids_in_combination_with_antispasmodics',
        'med_morphine_and_antispasmodics',
        'med_ketobemidone_and_antispasmodics',
        'med_pethidine_and_antispasmodics',
        'med_hydromorphone_and_antispasmodics',
        'med_opioids_in_combination_with_non-opioid_analgesics',
        'med_dihydrocodeine_and_paracetamol',
        'med_dihydrocodeine_and_acetylsalicylic_acid',
        'med_dihydrocodeine_and_other_non-opioid_analgesics',
        'med_codeine_and_paracetamol',
        'med_codeine_and_acetylsalicylic_acid',
        'med_codeine_and_ibuprofen',
        'med_codeine_and_other_non-opioid_analgesics',
        'med_tramadol_and_paracetamol',
        'med_tramadol_and_dexketoprofen',
        'med_tramadol_and_other_non-opioid_analgesics',
        'med_oxycodone_and_paracetamol',
        'med_oxycodone_and_acetylsalicylic_acid',
        'med_oxycodone_and_ibuprofen',
        'med_other_opioids',
        'med_tilidine',
        'med_tramadol',
        'med_dezocine',
        'med_meptazinol',
        'med_tapentadol']

B01AA = ['med_vitamin_k_antagonists',
         'med_dicoumarol',
         'med_phenindione',
         'med_warfarin',
         'med_phenprocoumon',
         'med_acenocoumarol',
         'med_ethyl_biscoumacetate',
         'med_clorindione',
         'med_diphenadione',
         'med_tioclomarol',
         'med_fluindione']

B01AB = ['med_heparin_group',
         'med_heparin',
         'med_antithrombin_iii',
         'med_dalteparin',
         'med_enoxaparin',
         'med_nadroparin',
         'med_parnaparin',
         'med_reviparin',
         'med_danaparoid',
         'med_tinzaparin',
         'med_sulodexide',
         'med_bemiparin',
         'med_heparin_combinations']

B01AE = ['med_direct_thrombin_inhibitors',
         'med_desirudin',
         'med_lepirudin',
         'med_argatroban',
         'med_melagatran',
         'med_ximelagatran',
         'med_bivalirudin',
         'med_dabigatran_etexilate']

B01AF = ['med_direct_factor_xa_inhibitors',
         'med_rivaroxaban',
         'med_apixaban',
         'med_edoxaban',
         'med_betrixaban']

B01AX = ['med_other_antithrombotic_agents',
         'med_defibrotide',
         'med_dermatan_sulfate',
         'med_fondaparinux',
         'med_caplacizumab']

C03C = ['med_high-ceiling_diuretics',
        'med_sulfonamides_plain',
        'med_furosemide',
        'med_bumetanide',
        'med_piretanide',
        'med_torasemide',
        'med_sulfonamides_and_potassium_in_combination',
        'med_furosemide_and_potassium',
        'med_bumetanide_and_potassium',
        'med_aryloxyacetic_acid_derivatives',
        'med_etacrynic_acid',
        'med_tienilic_acid',
        'med_pyrazolone_derivatives',
        'med_muzolimine',
        'med_other_high-ceiling_diuretics',
        'med_etozolin', ]

R05C = ['med_expectorants_excl_combinations_with_cough_suppressants',
        'med_expectorants',
        'med_tyloxapol',
        'med_potassium_iodide',
        'med_guaifenesin',
        'med_ipecacuanha',
        'med_althea_root',
        'med_senega',
        'med_antimony_pentasulfide',
        'med_creosote',
        'med_guaiacolsulfonate',
        'med_combinations',
        'med_levoverbenone',
        'med_hederae_helicis_folium',
        'med_cineole',
        'med_mucolytics',
        'med_acetylcysteine',
        'med_bromhexine',
        'med_carbocisteine',
        'med_eprazinone',
        'med_mesna',
        'med_ambroxol',
        'med_sobrerol',
        'med_domiodol',
        'med_letosteine',
        'med_combinations',
        'med_stepronin',
        'med_dornase_alfa_(desoxyribonuclease)',
        'med_neltenexine',
        'med_erdosteine',
        'med_mannitol']

R03A = ['med_adrenergics_inhalants',
        'med_alpha-_and_beta-adrenoreceptor_agonists',
        'med_epinephrine',
        'med_non-selective_beta-adrenoreceptor_agonists',
        'med_isoprenaline',
        'med_orciprenaline',
        'med_selective_beta-2-adrenoreceptor_agonists',
        'med_salbutamol',
        'med_terbutaline',
        'med_fenoterol',
        'med_rimiterol',
        'med_hexoprenaline',
        'med_isoetarine',
        'med_pirbuterol',
        'med_tretoquinol',
        'med_carbuterol',
        'med_tulobuterol',
        'med_salmeterol',
        'med_formoterol',
        'med_clenbuterol',
        'med_reproterol',
        'med_procaterol',
        'med_bitolterol',
        'med_indacaterol',
        'med_olodaterol',
        'med_combinations_of_adrenergics',
        'med_adrenergics_in_combination_with_corticosteroids_or_other_drugs_excl_anticholinergics',
        'med_epinephrine_and_other_drugs_for_obstructive_airway_diseases',
        'med_isoprenaline_and_other_drugs_for_obstructive_airway_diseases',
        'med_salbutamol_and_sodium_cromoglicate',
        'med_reproterol_and_sodium_cromoglicate',
        'med_salmeterol_and_fluticasone',
        'med_formoterol_and_budesonide',
        'med_formoterol_and_beclometasone',
        'med_formoterol_and_mometasone',
        'med_vilanterol_and_fluticasone_furoate',
        'med_formoterol_and_fluticasone',
        'med_salmeterol_and_budesonide',
        'med_salbutamol_and_beclometasone',
        'med_indacaterol_and_mometasone',
        'med_adrenergics_in_combination_with_anticholinergics_incl_triple_combinations_with_corticosteroids',
        'med_fenoterol_and_ipratropium_bromide',
        'med_salbutamol_and_ipratropium_bromide',
        'med_vilanterol_and_umeclidinium_bromide',
        'med_indacaterol_and_glycopyrronium_bromide',
        'med_formoterol_and_aclidinium_bromide',
        'med_olodaterol_and_tiotropium_bromide',
        'med_formoterol_and_glycopyrronium_bromide',
        'med_vilanterol_umeclidinium_bromide_and_fluticasone_furoate',
        'med_formoterol_glycopyrronium_bromide_and_beclometasone',
        'med_formoterol_and_tiotropium_bromide',
        'med_formoterol_glycopyrronium_bromide_and_budesonide',
        'med_indacaterol_glycopyrronium_bromide_and_mometasone']

R03B = ['med_other_drugs_for_obstructive_airway_diseases_inhalants',
        'med_glucocorticoids',
        'med_beclometasone',
        'med_budesonide',
        'med_flunisolide',
        'med_betamethasone',
        'med_fluticasone',
        'med_triamcinolone',
        'med_mometasone',
        'med_ciclesonide',
        'med_fluticasone_furoate',
        'med_anticholinergics',
        'med_ipratropium_bromide',
        'med_oxitropium_bromide',
        'med_stramoni_preparations',
        'med_tiotropium_bromide',
        'med_aclidinium_bromide',
        'med_glycopyrronium_bromide',
        'med_umeclidinium_bromide',
        'med_revefenacin',
        'med_tiotropium_bromide_combinations',
        'med_antiallergic_agents_excl_corticosteroids',
        'med_cromoglicic_acid',
        'med_nedocromil',
        'med_other_drugs_for_obstructive_airway_diseases_inhalants',
        'med_fenspiride']

C01CA03 = ['med_norepinephrine']

C01CA04 = ['med_dopamine']

C01CA24 = ['med_epinephrine']

H01BA01 = ['med_vasopressin_(argipressin)']

H01BA04 = ['med_terlipressin']

H02A = ['med_corticosteroids_for_systemic_use_plain',
        'med_mineralocorticoids',
        'med_aldosterone',
        'med_fludrocortisone',
        'med_desoxycortone',
        'med_glucocorticoids',
        'med_betamethasone',
        'med_dexamethasone',
        'med_fluocortolone',
        'med_methylprednisolone',
        'med_paramethasone',
        'med_prednisolone',
        'med_prednisone',
        'med_triamcinolone',
        'med_hydrocortisone',
        'med_cortisone',
        'med_prednylidene',
        'med_rimexolone',
        'med_deflazacort',
        'med_cloprednol',
        'med_meprednisone',
        'med_cortivazol']

MEDICATIONS = N01 + N05 + M03 + C01C + N02A + B01AA + B01AB + B01AE + B01AF + B01AX + C03C + R05C + R03A + R03B + \
              C01CA03 + C01CA04 + C01CA24 + H01BA01 + H01BA04 + H02A

